# Generated by Django 2.2.11 on 2020-06-02 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(blank=True, max_length=100, null=True)),
                ('M_price', models.IntegerField(blank=True, null=True)),
                ('M_quantity', models.IntegerField(blank=True, null=True)),
                ('M_saller', models.CharField(blank=True, max_length=50, null=True)),
                ('M_comapany', models.CharField(max_length=100)),
                ('M_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
