# Generated by Django 2.2.11 on 2020-07-25 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0007_auto_20200724_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='M_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 25, 11, 2, 27, 50453), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 25, 11, 2, 27, 48267), null=True),
        ),
    ]
