# Generated by Django 2.2.11 on 2020-07-25 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0009_auto_20200725_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 25, 18, 54, 8, 330528), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 25, 18, 54, 8, 329638), null=True),
        ),
    ]
