# Generated by Django 2.2.11 on 2020-08-01 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0010_auto_20200725_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 1, 16, 53, 36, 27494), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 1, 16, 53, 36, 26935), null=True),
        ),
    ]
