# Generated by Django 2.2.11 on 2020-08-02 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0013_auto_20200802_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 2, 14, 20, 31, 155608), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 2, 14, 20, 31, 155121), null=True),
        ),
    ]
