# Generated by Django 2.2.11 on 2020-08-04 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0015_auto_20200802_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='industry_type',
        ),
        migrations.AddField(
            model_name='person_information',
            name='gst_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person_information',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 4, 10, 55, 56, 77265), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 4, 10, 55, 56, 76101), null=True),
        ),
    ]
