# Generated by Django 2.2.11 on 2020-08-04 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0016_auto_20200804_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_information',
            name='industry_type',
        ),
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 4, 11, 0, 42, 568822), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 4, 11, 0, 42, 568389), null=True),
        ),
    ]
