# Generated by Django 2.2.11 on 2020-08-04 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0017_auto_20200804_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instock',
            old_name='N_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='instock',
            old_name='N_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='instock',
            old_name='N_quantity',
            new_name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='instock',
            name='N_data',
        ),
        migrations.AddField(
            model_name='instock',
            name='Product_company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instock',
            name='Receiver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instock',
            name='bill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instock',
            name='product_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='instock',
            name='product_total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
